// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// getThetaC
List getThetaC(arma::vec spt, arma::vec f0, arma::vec mu, arma::vec thetaStart, List thetaControl);
RcppExport SEXP _exchreg_getThetaC(SEXP sptSEXP, SEXP f0SEXP, SEXP muSEXP, SEXP thetaStartSEXP, SEXP thetaControlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type spt(sptSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type f0(f0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mu(muSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type thetaStart(thetaStartSEXP);
    Rcpp::traits::input_parameter< List >::type thetaControl(thetaControlSEXP);
    rcpp_result_gen = Rcpp::wrap(getThetaC(spt, f0, mu, thetaStart, thetaControl));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_exchreg_getThetaC", (DL_FUNC) &_exchreg_getThetaC, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_exchreg(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
